//This file is generated automatically by pnpm run build:icons
export type IconName =
  | 'chevron-down'
  | 'companies'
  | 'dot-menu-sleep'
  | 'edit'
  | 'four-boxes'
  | 'google'
  | 'handshake'
  | 'logo'
  | 'logs'
  | 'mailchimp'
  | 'multibranch'
  | 'people'
  | 'plus-icon'
  | 'record-creted'
  | 'records'
  | 'search'
  | 'text'
  | 'trash'
  | 'workflow';
