import { Source } from './generate';

export const sources: Source[] = [
  // =============== ### Done ===================
  // {
  //   authType: 'API_KEY',
  //   name: 'elevenlabs',
  //   logoDomain: 'eleven-labs.com',
  //   apiKeys: ['xApiKey'],
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/konfig-sdks/openapi-examples/refs/heads/main/elevenlabs/openapi.yaml',
  //   serverUrl: 'https://api.elevenlabs.io',
  //   authorization: {
  //     type: 'Custom_Header',
  //     headers: [
  //       {
  //         key: 'x-api-key',
  //         value: 'xApiKey',
  //       },
  //     ],
  //   },
  //   categories: ['ai', 'communications'],
  //   description: 'Eleven Labs is an ai audio platform',
  // },
  // {
  //   name: 'slack',
  //   authType: 'OAUTH',
  //   authorizationUrl: 'https://slack.com/oauth/v2/authorize',
  //   tokenUrl: 'https://slack.com/api/oauth.v2.access',
  //   serverUrl: 'https://slack.com/api',
  //   categories: ['communications'],
  //   logoDomain: 'slack.com',
  //   description: 'Slack is a cloud-based team collaboration tool.',
  //   openapiSpec: 'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/slack.com/1.7.0/openapi.yaml',
  // },
  // TODO: Regenerate ashby, uses api-key
  // {
  //   authType: 'API_KEY',
  //   authorization: { type: 'Basic', usernameKey: 'API_KEY' },
  //   name: 'ashby',
  //   logoDomain: 'ashbyhq.com',
  //   openapiSpec: 'https://raw.githubusercontent.com/konfig-sdks/openapi-examples/refs/heads/main/ashby/openapi.yaml',
  //   serverUrl: 'https://api.ashbyhq.com',
  //   categories: ['hr', 'communications'],
  //   description: 'Ashby is a platform for managing your team’s onboarding, offboarding, and everything in between.',
  // },
  // {
  //   name: 'pinterest',
  //   openapiSpec: 'https://raw.githubusercontent.com/pinterest/api-description/main/v5/openapi.json',
  //   authType: 'OAUTH',
  //   authorizationUrl: 'https://www.pinterest.com/oauth',
  //   tokenUrl: 'https://api.pinterest.com/v5/oauth/token',
  //   serverUrl: 'https://api.pinterest.com/v5',
  //   logoDomain: 'pinterest.com',
  //   categories: ['social_media'],
  //   description: 'Pinterest is a social media platform that allows users to discover and save ideas.',
  // },
  // {
  //   name: 'vercel',
  //   apiKeys: ['TOKEN'],
  //   authType: 'API_KEY',
  //   authorization: { type: 'Bearer', tokenKey: 'TOKEN' },
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/vercel.com/0.0.1/openapi.yaml',
  //   logoDomain: 'vercel.com',
  //   categories: ['dev-tools'],
  //   description: 'Vercel is a cloud platform for static sites and Serverless Functions.',
  // },
  // {
  //   name: 'spotify',
  //   authType: 'OAUTH',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/refs/heads/main/APIs/spotify.com/1.0.0/openapi.yaml',
  //   logoDomain: 'spotify.com',
  //   authorizationUrl: 'https://accounts.spotify.com/authorize',
  //   tokenUrl: 'https://accounts.spotify.com/api/token',
  //   serverUrl: 'https://api.spotify.com/v1',
  // },
  // {
  //   name: 'stripe',
  //   serverUrl: 'https://api.stripe.com',
  //   authType: 'API_KEY',
  //   apiKeys: ['API_KEY'],
  //   authorization: { type: 'Basic', usernameKey: 'API_KEY' },
  //   openapiSpec: 'https://raw.githubusercontent.com/tonyxiao/openSDKs/main/sdks/sdk-stripe/stripe.oas.json',
  //   logoDomain: 'stripe.com',
  //   categories: ['payments'],
  //   description: 'Stripe is a technology company that builds economic infrastructure for the internet.',
  // },
  {
    name: 'salesloft',
    authType: 'OAUTH',
    openapiSpec:
      'https://raw.githubusercontent.com/APIs-guru/openapi-directory/refs/heads/main/APIs/salesloft.com/v2/openapi.yaml',
    logoDomain: 'salesloft.com',
    authorizationUrl: 'https://accounts.salesloft.com/oauth/authorize',
    tokenUrl: 'https://accounts.salesloft.com/oauth/token',
    serverUrl: 'https://api.salesloft.com',
    categories: ['communications', 'crm', 'marketing'],
    description:
      'SalesLoft is a sales engagement platform that helps sales teams generate more meetings, manage their pipeline, and close more deals.',
  },
  // {
  //   name: 'intercom',
  //   authType: 'OAUTH',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/intercom/Intercom-OpenAPI/refs/heads/main/descriptions/2.9/api.intercom.io.yaml',
  //   logoDomain: 'intercom.com',
  //   authorizationUrl: 'https://app.intercom.com/oauth',
  //   tokenUrl: 'https://api.intercom.io/auth/eagle/token',
  //   serverUrl: 'https://api.intercom.io',
  //   categories: ['communications', 'crm', 'support'],
  //   description: 'Intercom is a customer messaging platform that helps businesses connect with customers.',
  // },
  // {
  //   name: 'quickbooks',
  //   authType: 'OAUTH',
  //   openapiSpec: 'https://raw.githubusercontent.com/tonyxiao/openSDKs/refs/heads/main/sdks/sdk-qbo/qbo.oas.json',
  //   logoDomain: 'quickbooks.intuit.com',
  //   authorizationUrl: 'https://appcenter.intuit.com/connect/oauth2',
  //   tokenUrl: 'https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer',
  //   serverUrl: 'https://quickbooks.api.intuit.com',
  // },
  // {
  //   name: 'notion',
  //   authType: 'OAUTH',
  //   openapiSpec: 'https://raw.githubusercontent.com/tonyxiao/openSDKs/main/sdks/sdk-notion/notion.oas.json',
  //   logoDomain: 'notion.so',
  //   authorizationUrl: 'https://api.notion.com/v1/oauth/authorize',
  //   tokenUrl: 'https://api.notion.com/v1/oauth/token',
  //   serverUrl: 'https://api.notion.com',
  //   categories: ['support', 'crm', 'productivity', 'spreadsheet'],
  //   description: 'Notion is an all-in-one workspace for notes, tasks, wikis, and databases.',
  // },
  // {
  //   name: 'lever',
  //   authType: 'OAUTH',
  //   openapiSpec: 'https://raw.githubusercontent.com/tonyxiao/openSDKs/main/sdks/sdk-lever/lever.oas.json',
  //   logoDomain: 'lever.co',
  //   authorizationUrl: 'https://auth.lever.co/authorize',
  //   tokenUrl: 'https://auth.lever.co/oauth/token',
  //   serverUrl: 'https://api.lever.co/v1',
  // },
  // {
  //   name: 'greenhouse',
  //   authType: 'API_KEY',
  //   apiKeys: ['API_TOKEN'],
  //   authorization: { type: 'Basic', usernameKey: 'API_TOKEN' },
  //   openapiSpec: 'https://raw.githubusercontent.com/tonyxiao/openSDKs/main/sdks/sdk-greenhouse/greenhouse.oas.json',
  //   logoDomain: 'greenhouse.io',
  //   serverUrl: 'https://harvest.greenhouse.io',
  //   categories: ['hr', 'communications', 'ats'],
  //   description:
  //     'Greenhouse is a recruiting software company that helps companies build and scale their recruiting process.',
  // },
  // {
  //   name: 'gong',
  //   serverUrl: 'https://api.gong.io',
  //   authType: 'API_KEY',
  //   apiKeys: ['ACCESS_KEY', 'ACCESS_KEY_SECRET'],
  //   authorization: { type: 'Basic', usernameKey: 'ACCESS_KEY', passwordKey: 'ACCESS_KEY_SECRET' },
  //   openapiSpec: 'https://raw.githubusercontent.com/tonyxiao/openSDKs/main/sdks/sdk-discord/discord.oas.json',
  //   logoDomain: 'gong.io',
  // },
  // {
  //   name: 'discord',
  //   serverUrl: 'https://discord.com/api/v10',
  //   authType: 'OAUTH',
  //   authorizationUrl: 'discord.com/oauth2/authorize',
  //   tokenUrl: 'https://discord.com/api/oauth2/token',
  //   openapiSpec: 'https://raw.githubusercontent.com/tonyxiao/openSDKs/main/sdks/sdk-discord/discord.oas.json',
  //   logoDomain: 'discord.com',
  // },
  // {
  //   name: 'dropbox',
  //   serverUrl: 'https://api.dropbox.com',
  //   authType: 'OAUTH',
  //   authorizationUrl: 'https://www.dropbox.com/oauth2/authorize',
  //   tokenUrl: 'https://api.dropboxapi.com/oauth2/token',
  //   openapiSpec: 'https://raw.githubusercontent.com/tonyxiao/openSDKs/main/sdks/sdk-dropbox/dropbox.oas.json',
  //   logoDomain: 'dropbox.com',
  // },
  // {
  //   name: 'coda',
  //   serverUrl: 'https://coda.io/apis/v1',
  //   authorization: {
  //     type: 'Bearer',
  //     tokenKey: 'API_KEY',
  //   },
  //   authType: 'API_KEY',
  //   openapiSpec: 'https://raw.githubusercontent.com/tonyxiao/openSDKs/main/sdks/sdk-coda/coda.oas.json',
  //   apiKeys: ['API_KEY'],
  //   logoDomain: 'coda.io',
  // },
  // {
  //   name: 'apollo',
  //   logoDomain: 'apollo.io',
  //   authType: 'API_KEY',
  //   apiKeys: ['API_KEY'],
  //   authorization: {
  //     type: 'Custom_Header',
  //     headers: [
  //       {
  //         key: 'X-Api-Key',
  //         value: 'API_KEY',
  //       },
  //     ],
  //   },
  //   serverUrl: 'https://app.apollo.io/api',
  //   openapiSpec: 'https://raw.githubusercontent.com/tonyxiao/openSDKs/main/sdks/sdk-apollo/apollo.oas.json',
  //   categories: ['communications', 'marketing', 'ats', 'hiring'],
  //   description:
  //     'Apollo is a sales engagement platform that helps sales teams generate more meetings, manage their pipeline, and close more deals.',
  // },
  // {
  //   name: 'figma',
  //   logoDomain: 'figma.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://www.figma.com/api/oauth/token',
  //   serverUrl: 'https://api.figma.com',
  //   authorizationUrl: 'https://www.figma.com/oauth',
  //   openapiSpec: 'https://raw.githubusercontent.com/figma/rest-api-spec/refs/heads/main/openapi/openapi.yaml',
  // },
  // {
  //   name: 'google-ads',
  //   logoDomain: 'google.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://www.googleapis.com/oauth2/v3/token',
  //   serverUrl: 'https://adsense.googleapis.com',
  //   authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/googleapis.com/adsense/v2/openapi.yaml',
  //   categories: ['marketing'],
  //   description: 'Google Ads is an online advertising platform developed by Google.',
  // },
  // {
  //   name: 'google-docs',
  //   logoDomain: 'google.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://oauth2.googleapis.com/token',
  //   serverUrl: 'https://docs.googleapis.com',
  //   authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/googleapis.com/docs/v1/openapi.yaml',
  //   categories: ['storage', 'accounting', 'communications'],
  //   description: 'Google Docs is a word processor included as part of a free, web-based software office suite.',
  // },
  // {
  //   name: 'google-calendar',
  //   logoDomain: 'google.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://oauth2.googleapis.com/token',
  //   serverUrl: 'https://www.googleapis.com/calendar/v3',
  //   authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/googleapis.com/calendar/v3/openapi.yaml',
  //   categories: ['calendar', 'scheduling', 'ai&automation'],
  //   description: 'Google Calendar is a time-management and scheduling calendar service developed by Google.',
  // },
  // {
  //   name: 'google-mail',
  //   logoDomain: 'google.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://oauth2.googleapis.com/token',
  //   serverUrl: 'https://gmail.googleapis.com',
  //   authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/googleapis.com/gmail/v1/openapi.yaml',
  //   categories: ['automation', 'communications', 'marketing', 'support'],
  //   description: 'Google Mail is a free email service developed by Google.',
  // },
  // {
  //   name: 'google-drive',
  //   logoDomain: 'google.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://oauth2.googleapis.com/token',
  //   serverUrl: 'https://www.googleapis.com/drive/v3',
  //   authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/googleapis.com/drive/v3/openapi.yaml',
  //   description: 'Google Drive is a file storage and synchronization service developed by Google.',
  //   categories: ['storage'],
  // },
  // {
  //   name: 'google-sheet',
  //   logoDomain: 'google.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://oauth2.googleapis.com/token',
  //   serverUrl: 'https://sheets.googleapis.com',
  //   authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/googleapis.com/sheets/v4/openapi.yaml',
  //   categories: ['spreadsheet', 'hr'],
  //   description: 'Google Sheets is a spreadsheet program included as part of a free, web-based software office suite.',
  // },
  // {
  //   name: 'ragie',
  //   logoDomain: 'ragie.ai',
  //   authType: 'API_KEY',
  //   apiKeys: ['API_KEY'],
  //   serverUrl: 'https://api.ragie.ai',
  //   openapiSpec: 'https://docs.ragie.ai/openapi/66587e474bcc890050cface6',
  // },
  // {
  //   name: 'claude',
  //   logoDomain: 'anthropic.com',
  //   authType: 'API_KEY',
  //   apiKeys: ['ANTHROPIC_API_KEY'],
  //   serverUrl: 'https://api.anthropic.com/v1',
  //   authorization: { type: 'Custom_Header', headers: [{ key: 'x-api-key', value: 'ANTHROPIC_API_KEY' }] },
  //   openapiSpec: 'https://raw.githubusercontent.com/tryAGI/Anthropic/main/docs/openapi.yaml',
  // },
  // {
  //   name: 'brex',
  //   logoDomain: 'brex.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://accounts-api.brex.com/oauth2/default/v1/token',
  //   serverUrl: 'https://platform.brexapis.com',
  //   authorizationUrl: 'https://accounts-api.brex.com/oauth2/default/v1/authorize',
  //   openapiSpec: 'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/brex.io/2021.12/openapi.yaml',
  // },
  // {
  //   name: 'clickup',
  //   logoDomain: 'clickup.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'api/v2/oauth/token',
  //   serverUrl: 'https://api.clickup.com',
  //   authorizationUrl: '/api',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/clickup.com/1.0.0/openapi.yaml',
  // },
  // {
  //   name: 'shopify',
  //   logoDomain: 'shopify.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://${this.config.SHOPIFY_SUBDOMAIN}.myshopify.com/admin/oauth/access_token',
  //   serverUrl: 'https://${this.config.SHOPIFY_SUBDOMAIN}.myshopify.com',
  //   authorizationUrl: 'https://${this.config.SHOPIFY_SUBDOMAIN}.myshopify.com/admin/oauth/authorize',
  //   configKeys: ['SHOPIFY_SUBDOMAIN'],
  //   openapiSpec: 'https://raw.githubusercontent.com/allengrant/shopify_openapi/master/shopify_openapi.json',
  // },
  // {
  //   name: 'docusign',
  //   logoDomain: 'docusign.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://account.docusign.com/oauth/token',
  //   serverUrl: 'https://www.docusign.net',
  //   authorizationUrl: 'https://account.docusign.com/oauth/auth',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/docusign.net/v2.1/openapi.yaml',
  // },
  // {
  //   name: 'instagram',
  //   logoDomain: 'instagram.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://api.instagram.com/oauth/access_token',
  //   serverUrl: 'https://api.instagram.com/v1',
  //   authorizationUrl: 'https://api.instagram.com/oauth/authorize',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/instagram.com/1.0.0/swagger.yaml',
  // },
  // {
  //   name: 'jira',
  //   logoDomain: 'atlassian.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://auth.atlassian.com/oauth/token',
  //   serverUrl: 'https:/${this.config.ATLASSIAN_SUBDOMAIN}.atlassian.net',
  //   configKeys: ['ATLASSIAN_SUBDOMAIN'],
  //   authorizationUrl: 'https://auth.atlassian.com/authorize',
  //   openapiSpec: 'https://developer.atlassian.com/cloud/jira/platform/swagger-v3.json',
  //   categories: ['ticketing', 'support'],
  //   description:
  //     'Jira is a proprietary issue tracking product developed by Atlassian that allows bug tracking and agile project management.',
  // },
  // {
  //   name: 'gusto',
  //   logoDomain: 'gusto.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://api.gusto.com/oauth/token',
  //   serverUrl: 'https://api.gusto.com',
  //   authorizationUrl: 'https://api.gusto.com/oauth/authorize',
  //   openapiSpec: 'https://raw.githubusercontent.com/Gusto-API/api.gusto.dev/master/reference/Gusto-API.v1.yaml',
  // },
  // {
  //   name: 'resend',
  //   logoDomain: 'resend.com',
  //   authType: 'API_KEY',
  //   apiKeys: ['API_KEY'],
  //   serverUrl: 'https://api.resend.com',
  //   openapiSpec: 'https://raw.githubusercontent.com/resend/resend-openapi/main/resend.yaml',
  // },
  // {
  //   name: 'sendgrid',
  //   logoDomain: 'sendgrid.com',
  //   authType: 'API_KEY',
  //   apiKeys: ['API_KEY'],
  //   serverUrl: 'https://api.sendgrid.com',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/sendgrid.com/1.0.0/openapi.yaml',
  // },
  // {
  //   name: 'oura',
  //   logoDomain: 'ouraring.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://api.ouraring.com/oauth/token',
  //   serverUrl: 'https://api.ouraring.com',
  //   authorizationUrl: 'https://cloud.ouraring.com/oauth/authorize',
  //   openapiSpec: 'https://cloud.ouraring.com/v2/static/json/openapi-1.21.json',
  // },
  // {
  //   name: 'attio',
  //   logoDomain: 'attio.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://app.attio.com/oauth/token',
  //   serverUrl: 'https://app.attio.com',
  //   authorizationUrl: 'https://app.attio.com/authorize',
  //   openapiSpec: 'https://developers.attio.com/openapi/655e2ce3ace07f065aa1dd14',
  //   categories: ['crm'],
  //   description: 'Powerful, flexible and data-driven, Attio makes it easy to build the exact CRM your business needs.',
  // },
  // {
  //   name: 'openai',
  //   logoDomain: 'openai.com',
  //   authType: 'API_KEY',
  //   apiKeys: ['API_KEY'],
  //   authorization: { type: 'Bearer', tokenKey: 'API_KEY' },
  //   serverUrl: 'https://app.attio.com',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/openai.com/1.2.0/openapi.yaml',
  // },
  // {
  //   name: 'zoom',
  //   logoDomain: 'zoom.us',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://zoom.us/oauth/token',
  //   serverUrl: 'https://api.zoom.us/v2',
  //   authorizationUrl: 'https://zoom.us/oauth/authorize',
  //   openapiSpec: 'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/zoom.us/2.0.0/openapi.yaml',
  // },
  // {
  //   name: 'zendesk',
  //   logoDomain: 'zendesk.com',
  //   authType: 'OAUTH',
  //   configKeys: ['ZENDESK_SUBDOMAIN'],
  //   serverUrl: 'https://${this.config.ZENDESK_SUBDOMAIN}.zendesk.com',
  //   openapiSpec: 'https://developer.zendesk.com/zendesk/oas.yaml',
  //   tokenUrl: 'https://${this.config.ZENDESK_SUBDOMAIN}.zendesk.com/oauth/tokens',
  //   authorizationUrl: 'https://${this.config.ZENDESK_SUBDOMAIN}.zendesk.com/oauth/authorizations/new',
  //   categories: ['support', 'crm', 'automation', 'hr'],
  //   description:
  //     'Zendesk is a customer service software company that provides a cloud-based customer support platform.',
  // },
  // {
  //   name: 'Asana',
  //   logoDomain: 'asana.com',
  //   authType: 'OAUTH',
  //   serverUrl: 'https://app.asana.com/api/1.0',
  //   tokenUrl: '/-/oauth_token',
  //   authorizationUrl: '/-/oauth_authorize',
  //   openapiSpec: 'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/asana.com/1.0/openapi.yaml',
  //   description: 'Asana is a project management platform that helps teams track, manage, and complete work.',
  //   categories: ['project-management'],
  // },
  // {
  //   name: 'Twilio',
  //   logoDomain: 'twilio.com',
  //   authType: 'API_KEY',
  //   apiKeys: ['ACCOUNT_SID', 'AUTH_TOKEN'],
  //   idKey: 'sid',
  //   fallbackIdKey: `account_sid`,
  //   configIdKey: `ACCOUNT_SID`,
  //   authorization: { type: `Basic`, usernameKey: `ACCOUNT_SID`, passwordKey: `AUTH_TOKEN` },
  //   serverUrl: 'https://api.twilio.com',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/twilio.com/api/1.55.0/openapi.yaml',
  //   categories: ['communications'],
  //   description: 'Twilio is a cloud communications platform as a service company based in San Francisco, California.',
  // },
  // {
  //   serverUrl: 'https://api.github.com',
  //   name: 'github',
  //   logoDomain: 'github.com',
  //   authType: 'API_KEY',
  //   apiKeys: ['PERSONAL_ACCESS_TOKEN'],
  //   idKey: 'id',
  //   fallbackIdKey: `id`,
  //   configIdKey: `API_KEY`,
  //   authorization: { type: `Bearer`, tokenKey: `PERSONAL_ACCESS_TOKEN` },
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/github.com/api.github.com.2022-11-28/1.1.4/openapi.yaml',
  //   categories: ['dev-tools'],
  //   description:
  //     'GitHub is a development platform inspired by the way you work. From open source to business, you can host and review code, manage projects, and build software alongside millions of other developers.',
  // },
  // {
  //   name: 'salesforce',
  //   logoDomain: 'salesforce.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://login.salesforce.com/services/oauth2/token',
  //   serverUrl: 'https://api.salesforce.com',
  //   authorizationUrl: 'https://login.salesforce.com/services/oauth2/authorize',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/salesforce.local/einstein/2.0.1/openapi.yaml',
  //   description:
  //     'Salesforce is a customer relationship management solution that brings companies and customers together.',
  //   categories: ['crm'],
  // },
  // {
  //   name: 'hubspot',
  //   logoDomain: 'hubspot.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://api.hubapi.com/oauth/v1/token',
  //   serverUrl: 'https://api.hubapi.com',
  //   authorizationUrl: 'https://app.hubspot.com/oauth/authorize',
  //   openapiSpec: 'https://api.hubspot.com/api-catalog-public/v1/apis/automation/v4/actions',
  // },
  // {
  //   name: 'xero',
  //   logoDomain: 'xero.com',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://identity.xero.com/connect/token',
  //   serverUrl: 'https://api.xero.com/api.xro/2.0',
  //   authorizationUrl: 'https://login.xero.com/identity/connect/authorize',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/xero.com/xero_accounting/2.9.4/openapi.yaml',
  // },
  // ================== ### TODO ======================
  // {
  //   'name': 'apple-app-store',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/apple-app-store',
  //   'Auth Mode': 'APP_STORE',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.appstoreconnect.apple.com/v1/apps',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/apple.com/app-store-connect/1.4.1/openapi.yaml',
  // },
  // {
  //   'name': 'bitbucket',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/bitbucket',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://bitbucket.org/site/oauth2/access_token',
  //   'Proxy URL': 'https://api.bitbucket.org',
  //   'Authorization URL': 'https://bitbucket.org/site/oauth2/authorize',
  //   Category: 'dev-tools',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/bitbucket.org/2.0/openapi.yaml',
  // },
  // {
  //   'name': 'box',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/box',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.box.com/oauth2/token',
  //   'Proxy URL': 'https://api.box.com',
  //   'Authorization URL': 'https://account.box.com/api/oauth2/authorize',
  //   Category: 'knowledge-base, storage',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/box.com/2.0.0/openapi.yaml',
  // },
  // {
  //   'name': 'Braze',
  //   'Docs URL': '',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/tree/main/APIs/braze.com/1.0.0',
  // },
  // {
  //   'name': 'confluence',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/confluence',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: 'knowledge-base',
  //   'OpenAPI integration': 'https://developer.atlassian.com/cloud/confluence/swagger.v3.json',
  // },
  // {
  //   'name': 'digitalocean',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/digitalocean',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://cloud.digitalocean.com/v1/oauth/token',
  //   'Proxy URL': 'https://api.digitalocean.com',
  //   'Authorization URL': 'https://cloud.digitalocean.com/v1/oauth/authorize',
  //   Category: 'dev-tools',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/digitalocean.com/2.0/openapi.yaml',
  // },
  // {
  //   'name': 'github',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/github',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://github.com/login/oauth/access_token',
  //   'Proxy URL': 'https://api.github.com',
  //   'Authorization URL': 'https://github.com/login/oauth/authorize',
  //   Category: 'dev-tools, support, ticketing',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/github.com/api.github.com.2022-11-28/1.1.4/openapi.yaml',
  // },
  // {
  //   'name': 'gitlab',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/gitlab',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://gitlab.com/oauth/token',
  //   'Proxy URL': 'https://gitlab.com',
  //   'Authorization URL': 'https://gitlab.com/oauth/authorize',
  //   Category: 'dev-tools, ticketing',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/gitlab.com/v3/swagger.yaml',
  // },
  // {
  //   'name': 'google',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/google',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://oauth2.googleapis.com/token',
  //   'Proxy URL': 'https://www.googleapis.com',
  //   'Authorization URL': 'https://accounts.google.com/o/oauth2/v2/auth',
  //   Category: '',
  //   'OpenAPI integration': 'https://github.com/APIs-guru/openapi-directory/tree/main/APIs/googleapis.com',
  // },
  // {
  //   'name': 'harvest',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/harvest',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://id.getharvest.com/api/v2/oauth2/token',
  //   'Proxy URL': 'https://api.harvestapp.com',
  //   'Authorization URL': 'https://id.getharvest.com/oauth2/authorize',
  //   Category: 'productivity',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/jolicode/harvest-openapi-generator/master/generated/harvest-openapi.yaml',
  // },
  // {
  //   'name': 'helpscout-docs',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/helpscout',
  //   'Auth Mode': 'BASIC',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': 'https://docsapi.helpscout.net',
  //   'Authorization URL': '',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/haydenfulghum/helpscoutswagger/blob/master/helpscout.json',
  // },
  // {
  //   'name': 'klaviyo',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/klaviyo',
  //   'Auth Mode': 'API_KEY',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': 'https://a.klaviyo.com',
  //   'Authorization URL': '',
  //   Category: 'marketing',
  //   'OpenAPI integration': 'https://raw.githubusercontent.com/klaviyo/openapi/blob/main/openapi/stable.json',
  // },
  // {
  //   name: 'mailchimp',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://login.mailchimp.com/oauth2/token',
  //   authorizationUrl: 'https://login.mailchimp.com/oauth2/authorize',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/mailchimp.com/3.0.55/openapi.yaml',
  //   serverUrl: 'https://server.api.mailchimp.com/3.0',
  //   logoDomain: 'mailchimp.com',
  //   categories: ['marketing', 'communications', 'crm'],
  //   description:
  //     'Mailchimp is an all-in-one marketing platform that helps you manage and talk to your clients, customers, and other interested parties.',
  // },
  // {
  //   'name': 'Netlify',
  //   'Docs URL': '',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/netlify.com/2.16.0/swagger.yaml',
  // },
  // {
  //   'name': 'okta',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/okta',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://${connectionConfig.subdomain}.okta.com/oauth2/v1/token',
  //   'Proxy URL': '',
  //   'Authorization URL': 'https://${connectionConfig.subdomain}.okta.com/oauth2/v1/authorize',
  //   Category: '',
  //   'OpenAPI integration': 'https://github.com/okta/okta-management-openapi-spec/tree/master/dist/current',
  // },
  // {
  //   'name': 'pagerduty',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/pagerduty',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://app.pagerduty.com/oauth/token',
  //   'Proxy URL': 'https://api.pagerduty.com',
  //   'Authorization URL': 'https://app.pagerduty.com/oauth/authorize',
  //   Category: 'dev-tools',
  //   'OpenAPI integration': 'https://raw.githubusercontent.com/PagerDuty/api-schema/main/reference/REST/openapiv3.json',
  // },
  // {
  //   'name': 'pandadoc',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/pandadoc',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.pandadoc.com/oauth2/access_token',
  //   'Proxy URL': 'https://api.pandadoc.com',
  //   'Authorization URL': 'https://app.pandadoc.com/oauth2/authorize',
  //   Category: 'legal',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/PandaDoc/pandadoc-openapi-specification/main/openapi.json',
  // },
  // {
  //   'name': 'Paylocity',
  //   'Docs URL': '',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/paylocity.com/2/openapi.yaml',
  // },
  // {
  //   'name': 'paypal',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/paypal',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.paypal.com/v1/oauth2/token',
  //   'Proxy URL': '',
  //   'Authorization URL': 'https://www.paypal.com/signin/authorize',
  //   Category: 'payment',
  //   'OpenAPI integration': 'https://github.com/paypal/paypal-rest-api-specifications/tree/main/openapi',
  // },
  // {
  //   'name': 'peopledatalabs',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/peopledatalabs',
  //   'Auth Mode': 'API_KEY',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': 'https://api.peopledatalabs.com',
  //   'Authorization URL': '',
  //   Category: 'analytics',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/peopledatalabs/openAPI-specifications/blob/main/pdl-specs.json',
  // },
  // {
  //   'name': 'Pinecone',
  //   'Docs URL': '',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/pinecone.io/20230406.1/openapi.yaml',
  // },
  // {
  //   'name': 'posthog',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/posthog',
  //   'Auth Mode': 'API_KEY',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': 'https://${connectionConfig.subdomain}.posthog.com',
  //   'Authorization URL': '',
  //   Category: 'dev-tools',
  //   'OpenAPI integration': 'https://app.posthog.com/api/schema/',
  // },
  // {
  //   'name': 'ring-central',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/ring-central',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://platform.ringcentral.com/restapi/oauth/token',
  //   'Proxy URL': 'https://platform.ringcentral.com',
  //   'Authorization URL': 'https://platform.ringcentral.com/restapi/oauth/authorize',
  //   Category: 'support',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/ringcentral/engage-digital-api-docs/master/specs/engage-digital_openapi3.yaml',
  // },
  // {
  //   'name': 'sage',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/sage',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://oauth.accounting.sage.com/token',
  //   'Proxy URL': 'https://api.accounting.sage.com',
  //   'Authorization URL': 'https://www.sageone.com/oauth2/auth/central',
  //   Category: 'accounting, erp',
  //   'OpenAPI integration':
  //     'https://developer.sage.com/accounting/files/v3.0-swagger/Sage%20One%20Core%20API%20-%20ES.swagger.json',
  // },
  // {
  //   name: 'spotify',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://accounts.spotify.com/api/token',
  //   serverUrl: 'https://api.spotify.com/v1',
  //   categories: ['music'],
  //   authorizationUrl: 'https://accounts.spotify.com/authorize',
  //   logoDomain: 'spotify.com',
  //   description: 'Spotify is a digital music service that gives you access to millions of songs.',
  //   openapiSpec: 'https://developer.spotify.com/reference/web-api/open-api-schema.yaml',
  // },
  // {
  //   'name': 'squareup',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/squareup',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://connect.squareup.com/oauth2/token',
  //   'Proxy URL': 'https://connect.squareup.com',
  //   'Authorization URL': 'https://connect.squareup.com/oauth2/authorize',
  //   Category: 'payment',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/squareup.com/2.0/openapi.yaml',
  // },
  // {
  //   'name': 'stackexchange',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/stackexchange',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://stackoverflow.com/oauth/access_token/json',
  //   'Proxy URL': 'https://api.stackexchange.com',
  //   'Authorization URL': 'https://stackoverflow.com/oauth',
  //   Category: 'knowledge-base, support',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/stackexchange.com/2.0/openapi.yaml',
  // },
  // {
  //   'name': 'trello',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/trello',
  //   'Auth Mode': 'OAUTH1',
  //   Status: 'Backlog',
  //   'Token URL': 'https://trello.com/1/OAuthGetAccessToken',
  //   'Proxy URL': 'https://api.trello.com',
  //   'Authorization URL': 'https://trello.com/1/OAuthAuthorizeToken',
  //   Category: 'productivity, ticketing',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/trello.com/1.0/openapi.yaml',
  // },
  // {
  //   'name': 'twitter',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/twitter',
  //   'Auth Mode': 'OAUTH1',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.twitter.com/oauth/access_token',
  //   'Proxy URL': 'https://api.twitter.com',
  //   'Authorization URL': 'https://api.twitter.com/oauth/authorize',
  //   Category: 'marketing, social',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/twitter.com/current/2.62/openapi.yaml',
  // },
  // {
  //   'name': 'vimeo',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/vimeo',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.vimeo.com/oauth/access_token',
  //   'Proxy URL': 'https://api.vimeo.com',
  //   'Authorization URL': 'https://api.vimeo.com/oauth/authorize',
  //   Category: 'video',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/vimeo.com/3.4/openapi.yaml',
  // },
  // {
  //   'name': 'webflow',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/webflow',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.webflow.com/oauth/access_token',
  //   'Proxy URL': 'https://api.webflow.com',
  //   'Authorization URL': 'https://webflow.com/oauth/authorize',
  //   Category: 'dev-tools, design, cms',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/webflow.com/2023-03-23T154040Z/openapi.yaml',
  // },
  // {
  //   'name': 'xero',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/xero',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://identity.xero.com/connect/token',
  //   'Proxy URL': 'https://api.xero.com',
  //   'Authorization URL': 'https://login.xero.com/identity/connect/authorize',
  //   Category: 'accounting',
  //   'OpenAPI integration': 'https://github.com/APIs-guru/openapi-directory/tree/main/APIs/xero.com',
  // },
  // {
  //   'name': 'zapier-nla',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/zapier-nla',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://nla.zapier.com/oauth/token/',
  //   'Proxy URL': 'https://nla.zapier.com',
  //   'Authorization URL': 'https://nla.zapier.com/oauth/authorize/',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/zapier.com/nla/1.0.0/openapi.yaml',
  // },
  // {
  //   'name': 'zoho',
  //   'Docs URL': '',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://accounts.zoho.${connectionConfig.extension}/oauth/v2/token',
  //   'Proxy URL': 'https://www.zohoapis.${connectionConfig.extension}',
  //   'Authorization URL': 'https://accounts.zoho.${connectionConfig.extension}/oauth/v2/auth',
  //   Category: 'accounting',
  //   'OpenAPI integration': 'https://creator.zoho.com/api/v2/downloadOAS',
  // },
];
