export const sources = [
  // =============== ### Done ===================
  // {
  //   name: 'docusign',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://account.docusign.com/oauth/token',
  //   serverUrl: 'https://www.docusign.net',
  //   authorizationUrl: 'https://account.docusign.com/oauth/auth',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/docusign.net/v2.1/openapi.yaml',
  // },
  {
    name: 'instagram',
    authType: 'OAUTH',
    tokenUrl: 'https://api.instagram.com/oauth/access_token',
    serverUrl: 'https://api.instagram.com/v1',
    authorizationUrl: 'https://api.instagram.com/oauth/authorize',
    openapiSpec:
      'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/instagram.com/1.0.0/swagger.yaml',
  },
  // {
  //   name: 'jira',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://auth.atlassian.com/oauth/token',
  //   serverUrl: 'https://api.atlassian.com',
  //   authorizationUrl: 'https://auth.atlassian.com/authorize',
  //   openapiSpec: 'https://developer.atlassian.com/cloud/jira/platform/swagger-v3.json',
  // },
  // {
  //   name: 'gusto',
  //   authType: 'OAUTH',
  //   tokenUrl: 'https://api.gusto.com/oauth/token',
  //   serverUrl: 'https://api.gusto.com',
  //   authorizationUrl: 'https://api.gusto.com/oauth/authorize',
  //   openapiSpec: 'https://raw.githubusercontent.com/Gusto-API/api.gusto.dev/master/reference/Gusto-API.v1.yaml',
  // },
  // {
  //   name: 'resend',
  //   authType: 'API_KEY',
  //   apiKeys: ['API_KEY'],
  //   serverUrl: 'https://api.resend.com',
  //   openapiSpec: 'https://raw.githubusercontent.com/resend/resend-openapi/main/resend.yaml',
  // },
  // {
  //   name: 'sendgrid',
  //   authType: 'API_KEY',
  //   apiKeys: ['API_KEY'],
  //   serverUrl: 'https://api.sendgrid.com',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/sendgrid.com/1.0.0/openapi.yaml',
  // },
  {
    name: 'zoom',
    'Docs URL': 'https://docs.nango.dev/integrations/all/zoom',
    authType: 'OAUTH',
    tokenUrl: 'https://zoom.us/oauth/token',
    serverUrl: 'https://api.zoom.us/v2',
    authorizationUrl: 'https://zoom.us/oauth/authorize',
    openapiSpec: 'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/zoom.us/2.0.0/openapi.yaml',
  },
  // {
  //   name: 'zendesk',
  //   authType: 'OAUTH',
  //   configKeys: ['ZENDESK_SUBDOMAIN'],
  //   serverUrl: 'https://${this.config.ZENDESK_SUBDOMAIN}.zendesk.com',
  //   openapiSpec: 'https://developer.zendesk.com/zendesk/oas.yaml',
  //   tokenUrl: 'https://${this.config.ZENDESK_SUBDOMAIN}.zendesk.com/oauth/tokens',
  //   authorizationUrl: 'https://${this.config.ZENDESK_SUBDOMAIN}.zendesk.com/oauth/authorizations/new',
  // },
  // {
  //   name: 'Asana',
  //   authType: 'OAUTH',
  //   serverUrl: 'https://app.asana.com',
  //   tokenUrl: '/-/oauth_token',
  //   authorizationUrl: '/-/oauth_authorize',
  //   openapiSpec: 'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/asana.com/1.0/openapi.yaml',
  // },
  // {
  //   name: 'Twilio',
  //   authType: 'API_KEY',
  //   apiKeys: ['ACCOUNT_SID', 'AUTH_TOKEN'],
  //   idKey: 'sid',
  //   fallbackIdKey: `account_sid`,
  //   configIdKey: `ACCOUNT_SID`,
  //   authorization: { type: `Basic`, usernameKey: `ACCOUNT_SID`, passwordKey: `AUTH_TOKEN` },
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/twilio.com/api/1.55.0/openapi.yaml',
  // },
  // {
  //   name: 'github',
  //   authType: 'API_KEY',
  //   apiKeys: ['API_KEY'],
  //   idKey: 'id',
  //   fallbackIdKey: `id`,
  //   configIdKey: `API_KEY`,
  //   authorization: { type: `Basic`, usernameKey: `API_KEY` },
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/github.com/api.github.com.2022-11-28/1.1.4/openapi.yaml',
  // },
  // ================== ### TODO ======================
  // {
  //   'name': 'stripe',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/stripe',
  //   authType: 'API_KEY',
  //   configKeys: ['API_KEY'],
  //   idKey: 'id',
  //   fallbackIdKey: `id`,
  //   configIdKey: `API_KEY`,
  //   authorization: { type: `Basic`, usernameKey: `API_KEY` },
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/stripe.com/2022-11-15/openapi.yaml',
  // },
  // {
  //   'name': 'apple-app-store',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/apple-app-store',
  //   'Auth Mode': 'APP_STORE',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.appstoreconnect.apple.com/v1/apps',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/apple.com/app-store-connect/1.4.1/openapi.yaml',
  // },
  // {
  //   'name': 'attio',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/attio',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://app.attio.com/oauth/token',
  //   'Proxy URL': 'https://app.attio.com',
  //   'Authorization URL': 'https://app.attio.com/authorize',
  //   Category: 'crm',
  //   'OpenAPI integration': 'https://developers.attio.com/openapi/655e2ce3ace07f065aa1dd14',
  // },
  // {
  //   'name': 'bitbucket',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/bitbucket',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://bitbucket.org/site/oauth2/access_token',
  //   'Proxy URL': 'https://api.bitbucket.org',
  //   'Authorization URL': 'https://bitbucket.org/site/oauth2/authorize',
  //   Category: 'dev-tools',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/bitbucket.org/2.0/openapi.yaml',
  // },
  // {
  //   'name': 'box',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/box',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.box.com/oauth2/token',
  //   'Proxy URL': 'https://api.box.com',
  //   'Authorization URL': 'https://account.box.com/api/oauth2/authorize',
  //   Category: 'knowledge-base, storage',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/box.com/2.0.0/openapi.yaml',
  // },
  // {
  //   'name': 'Braze',
  //   'Docs URL': '',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/tree/main/APIs/braze.com/1.0.0',
  // },
  // {
  //   'name': 'brex',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/brex',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://accounts-api.brex.com/oauth2/default/v1/token',
  //   'Proxy URL': 'https://platform.brexapis.com',
  //   'Authorization URL': 'https://accounts-api.brex.com/oauth2/default/v1/authorize',
  //   Category: 'banking',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/brex.io/2021.12/openapi.yaml',
  // },
  // {
  //   name: 'clickup',
  //   authType: 'OAUTH',
  //   tokenUrl: 'api/v2/oauth/token',
  //   serverUrl: 'https://api.clickup.com',
  //   authorizationUrl: '/api',
  //   openapiSpec:
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/clickup.com/1.0.0/openapi.yaml',
  // },
  // {
  //   'name': 'confluence',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/confluence',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: 'knowledge-base',
  //   'OpenAPI integration': 'https://developer.atlassian.com/cloud/confluence/swagger.v3.json',
  // },
  // {
  //   'name': 'digitalocean',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/digitalocean',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://cloud.digitalocean.com/v1/oauth/token',
  //   'Proxy URL': 'https://api.digitalocean.com',
  //   'Authorization URL': 'https://cloud.digitalocean.com/v1/oauth/authorize',
  //   Category: 'dev-tools',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/digitalocean.com/2.0/openapi.yaml',
  // },

  // {
  //   'name': 'github',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/github',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://github.com/login/oauth/access_token',
  //   'Proxy URL': 'https://api.github.com',
  //   'Authorization URL': 'https://github.com/login/oauth/authorize',
  //   Category: 'dev-tools, support, ticketing',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/github.com/api.github.com.2022-11-28/1.1.4/openapi.yaml',
  // },
  // {
  //   'name': 'gitlab',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/gitlab',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://gitlab.com/oauth/token',
  //   'Proxy URL': 'https://gitlab.com',
  //   'Authorization URL': 'https://gitlab.com/oauth/authorize',
  //   Category: 'dev-tools, ticketing',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/gitlab.com/v3/swagger.yaml',
  // },
  // {
  //   'name': 'google',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/google',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://oauth2.googleapis.com/token',
  //   'Proxy URL': 'https://www.googleapis.com',
  //   'Authorization URL': 'https://accounts.google.com/o/oauth2/v2/auth',
  //   Category: '',
  //   'OpenAPI integration': 'https://github.com/APIs-guru/openapi-directory/tree/main/APIs/googleapis.com',
  // },
  // {
  //   'name': 'google-ads',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/google-ads',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': 'https://www.googleapis.com/oauth2/v3/token',
  //   'Proxy URL': 'https://googleads.googleapis.com',
  //   'Authorization URL': '',
  //   Category: 'marketing',
  //   'OpenAPI integration': 'see ^',
  // },
  // {
  //   'name': 'google-calendar',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/google-calendar',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': 'https://www.googleapis.com',
  //   'Authorization URL': '',
  //   Category: 'productivity',
  //   'OpenAPI integration': 'see ^',
  // },
  // {
  //   'name': 'google-docs',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/google-docs',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': 'https://docs.googleapis.com',
  //   'Authorization URL': '',
  //   Category: 'productivity',
  //   'OpenAPI integration': 'see ^',
  // },
  // {
  //   'name': 'google-drive',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/google-drive',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: 'knowledge-base, storage',
  //   'OpenAPI integration': 'see ^',
  // },
  // {
  //   'name': 'google-mail',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/google-mail',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': 'https://gmail.googleapis.com',
  //   'Authorization URL': '',
  //   Category: 'productivity',
  //   'OpenAPI integration': 'see ^',
  // },
  // {
  //   'name': 'google-sheet',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/google-sheet',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': 'https://sheets.googleapis.com',
  //   'Authorization URL': '',
  //   Category: 'productivity',
  //   'OpenAPI integration': 'see ^',
  // },
  // {
  //   'name': 'harvest',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/harvest',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://id.getharvest.com/api/v2/oauth2/token',
  //   'Proxy URL': 'https://api.harvestapp.com',
  //   'Authorization URL': 'https://id.getharvest.com/oauth2/authorize',
  //   Category: 'productivity',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/jolicode/harvest-openapi-generator/master/generated/harvest-openapi.yaml',
  // },
  // {
  //   'name': 'helpscout-docs',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/helpscout',
  //   'Auth Mode': 'BASIC',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': 'https://docsapi.helpscout.net',
  //   'Authorization URL': '',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/haydenfulghum/helpscoutswagger/blob/master/helpscout.json',
  // },
  // {
  //   'name': 'klaviyo',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/klaviyo',
  //   'Auth Mode': 'API_KEY',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': 'https://a.klaviyo.com',
  //   'Authorization URL': '',
  //   Category: 'marketing',
  //   'OpenAPI integration': 'https://raw.githubusercontent.com/klaviyo/openapi/blob/main/openapi/stable.json',
  // },
  // {
  //   'name': 'mailchimp',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/mailchimp',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://login.mailchimp.com/oauth2/token',
  //   'Proxy URL': '',
  //   'Authorization URL': 'https://login.mailchimp.com/oauth2/authorize',
  //   Category: 'marketing, surveys',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/mailchimp.com/3.0.55/openapi.yaml',
  // },
  // {
  //   'name': 'Netlify',
  //   'Docs URL': '',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/netlify.com/2.16.0/swagger.yaml',
  // },
  // {
  //   'name': 'okta',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/okta',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://${connectionConfig.subdomain}.okta.com/oauth2/v1/token',
  //   'Proxy URL': '',
  //   'Authorization URL': 'https://${connectionConfig.subdomain}.okta.com/oauth2/v1/authorize',
  //   Category: '',
  //   'OpenAPI integration': 'https://github.com/okta/okta-management-openapi-spec/tree/master/dist/current',
  // },
  // {
  //   'name': 'OpenAi',
  //   'Docs URL': '',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/openai.com/1.2.0/openapi.yaml',
  // },
  // {
  //   'name': 'oura',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/oura',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.ouraring.com/oauth/token',
  //   'Proxy URL': 'https://api.ouraring.com',
  //   'Authorization URL': 'https://cloud.ouraring.com/oauth/authorize',
  //   Category: 'sports',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/jordan-chalupka/ouraring/blob/master/ouraring_openapi.yaml',
  // },
  // {
  //   'name': 'pagerduty',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/pagerduty',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://app.pagerduty.com/oauth/token',
  //   'Proxy URL': 'https://api.pagerduty.com',
  //   'Authorization URL': 'https://app.pagerduty.com/oauth/authorize',
  //   Category: 'dev-tools',
  //   'OpenAPI integration': 'https://raw.githubusercontent.com/PagerDuty/api-schema/main/reference/REST/openapiv3.json',
  // },
  // {
  //   'name': 'pandadoc',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/pandadoc',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.pandadoc.com/oauth2/access_token',
  //   'Proxy URL': 'https://api.pandadoc.com',
  //   'Authorization URL': 'https://app.pandadoc.com/oauth2/authorize',
  //   Category: 'legal',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/PandaDoc/pandadoc-openapi-specification/main/openapi.json',
  // },
  // {
  //   'name': 'Paylocity',
  //   'Docs URL': '',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/paylocity.com/2/openapi.yaml',
  // },
  // {
  //   'name': 'paypal',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/paypal',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.paypal.com/v1/oauth2/token',
  //   'Proxy URL': '',
  //   'Authorization URL': 'https://www.paypal.com/signin/authorize',
  //   Category: 'payment',
  //   'OpenAPI integration': 'https://github.com/paypal/paypal-rest-api-specifications/tree/main/openapi',
  // },
  // {
  //   'name': 'pendo',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/pendo',
  //   'Auth Mode': 'API_KEY',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': 'https://app.pendo.io',
  //   'Authorization URL': '',
  //   Category: 'analytics',
  //   'OpenAPI integration': 'https://raw.githubusercontent.com/Band-Aid/pendo-openapi/blob/main/api/openapi.yaml',
  // },
  // {
  //   'name': 'peopledatalabs',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/peopledatalabs',
  //   'Auth Mode': 'API_KEY',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': 'https://api.peopledatalabs.com',
  //   'Authorization URL': '',
  //   Category: 'analytics',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/peopledatalabs/openAPI-specifications/blob/main/pdl-specs.json',
  // },
  // {
  //   'name': 'Pinecone',
  //   'Docs URL': '',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/pinecone.io/20230406.1/openapi.yaml',
  // },
  // {
  //   'name': 'pinterest',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/pinterest',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.pinterest.com/v5/oauth/token',
  //   'Proxy URL': 'https://api.pinterest.com',
  //   'Authorization URL': 'https://www.pinterest.com/oauth',
  //   Category: 'design, marketing, social, video',
  //   'OpenAPI integration': 'https://raw.githubusercontent.com/pinterest/api-description/main/v5/openapi.json',
  // },
  // {
  //   'name': 'posthog',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/posthog',
  //   'Auth Mode': 'API_KEY',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': 'https://${connectionConfig.subdomain}.posthog.com',
  //   'Authorization URL': '',
  //   Category: 'dev-tools',
  //   'OpenAPI integration': 'https://app.posthog.com/api/schema/',
  // },
  // {
  //   'name': 'quickbooks',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/quickbooks',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer',
  //   'Proxy URL': 'https://quickbooks.api.intuit.com',
  //   'Authorization URL': 'https://appcenter.intuit.com/connect/oauth2',
  //   Category: 'accounting',
  //   'OpenAPI integration': 'https://gist.githubusercontent.com/kinlane/8b67e8bb101500cbc1bce2a7ca49fffc/raw/ed304dd2ccf1142ae49266bb5f1bde7516378495/QuickBooks%2520Online%2520V3%2520API%2520OpenAPI.json',
  // },
  // {
  //   'name': 'ring-central',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/ring-central',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://platform.ringcentral.com/restapi/oauth/token',
  //   'Proxy URL': 'https://platform.ringcentral.com',
  //   'Authorization URL': 'https://platform.ringcentral.com/restapi/oauth/authorize',
  //   Category: 'support',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/ringcentral/engage-digital-api-docs/master/specs/engage-digital_openapi3.yaml',
  // },
  // {
  //   'name': 'sage',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/sage',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://oauth.accounting.sage.com/token',
  //   'Proxy URL': 'https://api.accounting.sage.com',
  //   'Authorization URL': 'https://www.sageone.com/oauth2/auth/central',
  //   Category: 'accounting, erp',
  //   'OpenAPI integration':
  //     'https://developer.sage.com/accounting/files/v3.0-swagger/Sage%20One%20Core%20API%20-%20ES.swagger.json',
  // },
  // {
  //   'name': 'salesloft',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/salesloft',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://accounts.salesloft.com/oauth/token',
  //   'Proxy URL': 'https://api.salesloft.com',
  //   'Authorization URL': 'https://accounts.salesloft.com/oauth/authorize',
  //   Category: 'marketing',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/salesloft.com/v2/openapi.yaml',
  // },
  // {
  //   'name': 'shopify',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/shopify',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://${connectionConfig.subdomain}.myshopify.com/admin/oauth/access_token',
  //   'Proxy URL': 'https://${connectionConfig.subdomain}.myshopify.com',
  //   'Authorization URL': 'https://${connectionConfig.subdomain}.myshopify.com/admin/oauth/authorize',
  //   Category: 'e-commerce',
  //   'OpenAPI integration': 'https://raw.githubusercontent.com/allengrant/shopify_openapi/master/shopify_openapi.json',
  // },
  // {
  //   'name': 'slack',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/slack',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://slack.com/api/oauth.v2.access',
  //   'Proxy URL': 'https://slack.com/api',
  //   'Authorization URL': 'https://slack.com/oauth/v2/authorize',
  //   Category: 'productivity',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/slack.com/1.7.0/openapi.yaml',
  // },
  // {
  //   'name': 'spotify',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/spotify',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://accounts.spotify.com/api/token',
  //   'Proxy URL': 'https://api.spotify.com',
  //   'Authorization URL': 'https://accounts.spotify.com/authorize',
  //   Category: 'other',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/spotify.com/1.0.0/openapi.yaml',
  // },
  // {
  //   'name': 'squareup',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/squareup',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://connect.squareup.com/oauth2/token',
  //   'Proxy URL': 'https://connect.squareup.com',
  //   'Authorization URL': 'https://connect.squareup.com/oauth2/authorize',
  //   Category: 'payment',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/squareup.com/2.0/openapi.yaml',
  // },
  // {
  //   'name': 'stackexchange',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/stackexchange',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://stackoverflow.com/oauth/access_token/json',
  //   'Proxy URL': 'https://api.stackexchange.com',
  //   'Authorization URL': 'https://stackoverflow.com/oauth',
  //   Category: 'knowledge-base, support',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/stackexchange.com/2.0/openapi.yaml',
  // },
  // {
  //   'name': 'trello',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/trello',
  //   'Auth Mode': 'OAUTH1',
  //   Status: 'Backlog',
  //   'Token URL': 'https://trello.com/1/OAuthGetAccessToken',
  //   'Proxy URL': 'https://api.trello.com',
  //   'Authorization URL': 'https://trello.com/1/OAuthAuthorizeToken',
  //   Category: 'productivity, ticketing',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/trello.com/1.0/openapi.yaml',
  // },
  // {
  //   'name': 'twilio',
  //   'Docs URL': '',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: '',
  //   'OpenAPI integration': 'https://github.com/APIs-guru/openapi-directory/tree/main/APIs/twilio.com',
  // },
  // {
  //   'name': 'twitter',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/twitter',
  //   'Auth Mode': 'OAUTH1',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.twitter.com/oauth/access_token',
  //   'Proxy URL': 'https://api.twitter.com',
  //   'Authorization URL': 'https://api.twitter.com/oauth/authorize',
  //   Category: 'marketing, social',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/twitter.com/current/2.62/openapi.yaml',
  // },
  // {
  //   'name': 'Vercel',
  //   'Docs URL': '',
  //   'Auth Mode': '',
  //   Status: 'Backlog',
  //   'Token URL': '',
  //   'Proxy URL': '',
  //   'Authorization URL': '',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/vercel.com/0.0.1/openapi.yaml',
  // },
  // {
  //   'name': 'vimeo',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/vimeo',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.vimeo.com/oauth/access_token',
  //   'Proxy URL': 'https://api.vimeo.com',
  //   'Authorization URL': 'https://api.vimeo.com/oauth/authorize',
  //   Category: 'video',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/vimeo.com/3.4/openapi.yaml',
  // },
  // {
  //   'name': 'webflow',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/webflow',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://api.webflow.com/oauth/access_token',
  //   'Proxy URL': 'https://api.webflow.com',
  //   'Authorization URL': 'https://webflow.com/oauth/authorize',
  //   Category: 'dev-tools, design, cms',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/webflow.com/2023-03-23T154040Z/openapi.yaml',
  // },
  // {
  //   'name': 'xero',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/xero',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://identity.xero.com/connect/token',
  //   'Proxy URL': 'https://api.xero.com',
  //   'Authorization URL': 'https://login.xero.com/identity/connect/authorize',
  //   Category: 'accounting',
  //   'OpenAPI integration': 'https://github.com/APIs-guru/openapi-directory/tree/main/APIs/xero.com',
  // },
  // {
  //   'name': 'zapier-nla',
  //   'Docs URL': 'https://docs.nango.dev/integrations/all/zapier-nla',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://nla.zapier.com/oauth/token/',
  //   'Proxy URL': 'https://nla.zapier.com',
  //   'Authorization URL': 'https://nla.zapier.com/oauth/authorize/',
  //   Category: '',
  //   'OpenAPI integration':
  //     'https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/zapier.com/nla/1.0.0/openapi.yaml',
  // },
  // {
  //   'name': 'zoho',
  //   'Docs URL': '',
  //   'Auth Mode': 'OAUTH2',
  //   Status: 'Backlog',
  //   'Token URL': 'https://accounts.zoho.${connectionConfig.extension}/oauth/v2/token',
  //   'Proxy URL': 'https://www.zohoapis.${connectionConfig.extension}',
  //   'Authorization URL': 'https://accounts.zoho.${connectionConfig.extension}/oauth/v2/auth',
  //   Category: 'accounting',
  //   'OpenAPI integration': 'https://creator.zoho.com/api/v2/downloadOAS',
  // },
];
