export const Labels = {
  CHAT: 'CHAT',
  SENT: 'SENT',
  INBOX: 'INBOX',
  IMPORTANT: 'IMPORTANT',
  TRASH: 'TRASH',
  DRAFT: 'DRAFT',
  SPAM: 'SPAM',
  CATEGORY_FORUMS: 'CATEGORY_FORUMS',
  CATEGORY_UPDATES: 'CATEGORY_UPDATES',
  CATEGORY_PERSONAL: 'CATEGORY_PERSONAL',
  CATEGORY_PROMOTIONS: 'CATEGORY_PROMOTIONS',
  CATEGORY_SOCIAL: 'CATEGORY_SOCIAL',
  STARRED: 'STARRED',
  UNREAD: 'UNREAD',
} as const;

export const GMAIL_API_URL = `https://gmail.googleapis.com`;

export const WORKSHEET_RECORD_TYPE_NAME = 'people';
