import { Mastra } from '@mastra/core';
import type { Metadata } from 'next';

import localFont from 'next/font/local';

import RepoSwitcher from '@/components/blocks/repo-switcher';

import { config } from '../../mastra.config';

import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { repo: string };
}>) {
  const { repo } = params;
  const framework = Mastra.init(config);
  const client = await framework.getIntegration('GITHUB').getApiClient({ connectionId: 'system' });

  const repos = await client['/orgs/{org}/repos'].get({
    params: {
      org: process.env.GIHUB_ORG || 'mastra-inc',
    },
  });
  const reposData = await repos.json();
  const repoNames = reposData.map((repo: any) => repo.name);
  console.log('repoNames', repoNames);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="hidden flex-col md:flex">
          <div className="border-b">
            <div className="flex h-16 items-center px-4">
              <RepoSwitcher repos={repoNames} defaultRepo={repo || 'future'} />
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
